#!/usr/bin/env php
<?php

$kernel = require_once __DIR__.'/bootstrap/autoload.php';

$kernel
    ->loadServices($after_module = false, [
        Clarity\Providers\Log::class,
        Clarity\Providers\Aliaser::class,
        Components\Providers\Application::class,
        Clarity\Providers\Auth::class,
        Clarity\Providers\Cache::class,
        Clarity\Providers\CollectionManager::class,
        Clarity\Providers\Console::class,
        Clarity\Providers\Crypt::class,
        Clarity\Providers\DB::class,
        Components\Providers\Dispatcher::class,
        Clarity\Providers\ErrorHandler::class,
        Clarity\Providers\Filter::class,
        Clarity\Providers\Flash::class,
        Clarity\Providers\FlashBag::class,
        Clarity\Providers\Flysystem::class,
        Clarity\Lang\LangServiceProvider::class,
        Clarity\Mail\MailServiceProvider::class,
        Clarity\Providers\MetadataAdapter::class,
        Clarity\Providers\Module::class,
        Clarity\Providers\Mongo::class,
        Clarity\Providers\Queue::class,
        Clarity\Providers\Redirect::class,
        Clarity\Providers\Request::class,
        Clarity\Providers\Response::class,
        Clarity\Providers\Router::class,
        Clarity\Providers\RouterAnnotations::class,
        Clarity\Providers\Session::class,
        Clarity\Providers\URL::class,
        Clarity\View\ViewServiceProvider::class,
    ]);

di()->get('console')->run();
