#!/usr/bin/env php
<?php

require_once __DIR__ . '/bootstrap/start.php';

$command = "php -S ".getenv('SERVE_HOST').":".getenv('SERVE_PORT')." -t ".__DIR__."/public ".__DIR__."/.htrouter.php";

echo 'Server is now running on: '.getenv('SERVE_HOST').':'.getenv('SERVE_PORT')."\n";

shell_exec($command);

exit;