#!/usr/bin/env php
<?php

require_once __DIR__ . '/bootstrap/autoload.php';

use Symfony\Component\Console\Application;
// use Symfony\Component\Console\Input\InputInterface;
// use Symfony\Component\Console\Output\OutputInterface;

$version = 'v0.0.1';

$application = new Application('Slayer (c) Daison Carino', $version);
foreach (slayer_config()->consoles as $console) {
    $application->add(new $console);
}

$application->run();